bf16: true
cutoff_len: 2048
dataset: trump
dataset_dir: data
ddp_timeout: 180000000
do_train: true
double_quantization: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: meta-llama/Llama-2-7b-chat-hf
num_train_epochs: 20.0
optim: adamw_torch
output_dir: saves/Llama-2-7B-Chat/lora/train_2025-01-17-08-49-44
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
quantization_bit: 8
quantization_method: hqq
report_to: none
save_steps: 100
stage: sft
template: llama2
trust_remote_code: true
warmup_steps: 0
